### ISSUE TITLE
functionality for [Today's Date]

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#11]
[today's date]
it will pop up a dialog box with the date

**Comment by iankilgore** [comment]
Instead of a dialog box, we need to make it so that somehow the time is hidden and for example, if it were April 29, it would say 4-29 on the display, and then the days of the week to the right with an arrow, oh, and when the date is showing, we also need to hide the AM/PM. The date will show for maybe 5 seconds.

**Comment by LeeKilgore** [comment]
moved to 2.0
