### ISSUE TITLE
change line indenting so that it is uniform

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#32]
change line indenting so that it is uniform

**Comment by iankilgore** [comment]
I changed some in index.html and moshiscripts.js but I think you need to help me with the rest because  I don't know exactly how it is supposed to look.

**Comment by LeeKilgore** [comment]
ok

**Comment by iankilgore** [comment]
I got it so that most of the line indenting is fixed, the way i did it was actually by typing it again in atom it will do line indenting for you, however towards the end, it makes up to 70 characters of indenting. you are going to have to help on that part, but what I really need help on is the light switch got moved to the bottom and the time is not showing, maybe take a look at the code and see if i missed a line or missed one character, whatever it is we need to get it fixed, revert to previous commits if you have to.
